FROM rockylinux:8.7
MAINTAINER Leonardo Loures <luvres@hotmail.com>

RUN \
  dnf install -y epel-release \
  && dnf install -y xorg-x11-server-Xorg xfwm4 xfce4-session xauth xkbcomp procps-ng xfce4-settings wmctrl xfce4-terminal \
  && dnf install -y https://yum.osc.edu/ondemand/3.0/compute/el8Server/x86_64/python3-websockify-0.10.0-1.el8.noarch.rpm \
  && dnf install -y https://yum.osc.edu/ondemand/3.0/compute/el8Server/x86_64/turbovnc-2.2.5-1.el8.x86_64.rpm \
  && dnf clean all
